name: zentra
description: "Zentra - Gestión inteligente para micronegocios."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  intl: ^0.20.3
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
